### ISSUE TITLE
FEATURE - RUN demo file in browser

### ISSUE THREAD

**Issue by wojciechteclaw** [LBD-Hackers/IFC-LBD#2]
After building the application using a live server, the application doesn't start automatically in the browser.

**Comment by wojciechteclaw** [comment]
In the reference to pull requests: #3 and #4

**Comment by MadsHolten** [comment]
The thing is that I haven't really succeeded in running the tool in the browser. Only in NodeJS

**Comment by MadsHolten** [comment]
It should work now!
