### ISSUE TITLE
LBDParser parse method return error for duplex

### ISSUE THREAD

**Issue by wojciechteclaw** [LBD-Hackers/IFC-LBD#6]
Hi, 
I'm getting the following error while parsing Duplex house model:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '@context')
    at index.js:57373:1
    at new Promise (<anonymous>)
    at concatJSONLD (index.js:57372:1)
    at LBDParser.parse (index.js:58745:1)`

My code:

[Playground Link](https://www.typescriptlang.org/play?#code/AQ4BwJwSwNwQwC4FNhwM4E8B2BjYB7GJCAd2mQBkAhAEQAU4I1iB1KBACwGUkEEosAczQAKZnwHCAXMAZNiPCULQBKYAG8AsAChQe4JyhoAdABsARgBM5zCMAC8wLEhLBq9RrbG9+ylQG4dPQBfHSDQMABXc1MoPHRseLAwJCxLADEoUyQAFXwASQAzHABBOnyRQqykGUzsgBpgcV9pWU8FH0lVDXD9VBI4dgMOI2NCYjJ2JHcbVnZuTuVvJWEA3v1shGAq7KpIwsLiB37BrcMTCCQ4S3ysKIQ6pErqlWNOVJEUewA+YBR0YAlCAQOAYPYHYgUKAAayQa10fWAm3A7Us4MOdkczlcAFUBAgABxAkEYZ67fYY+GI4ajKDFMr5YwAeRSWAAsvhLEhTCIwKj0cQqYjkQhoGBsmhjnABkNzmYrLMIMY+fIRHK6aVyo0AAyvd5YT4OX5wwIIvrIgCOkWuaGJoKlMrOIxMgl4AEVrZY0OkIPgALY5MUStVBpCqN4cD5fY1CvpytAIfCXYzXSyBqDisMiK02u0YWPAULadaQWCIf6YXDAV0ID02n3+9OZ0SijMSmRwLD5mR0X1+oxIAA8ecHdcs31+WjN+hw+CwCeAACs0HOKJYHaclyusKZLG98AAlGjpENtsOoSXLue74wAKW3a5o+BwkT9qQQBb0lwQkQgWGATLmIuSA4AgxjwKYkRZleWBrq8fpwGAIifGoPzADQtCIHAADCc6ivgpjZEqNZjg2AahihBZFiW0DwMgTQIIgcTVu6npkU22SnpmHZdmoU7Ut+v7-jmlhcdkxhoNEwGgY0raZsqlyWHE5ayaGYxASBCCqWexiCCCYAcFRQA)

For BOT, PRODUCT, and FSO it works.

**Comment by MadsHolten** [comment]
Did you fix this?

**Comment by wojciechteclaw** [comment]
Yes
